SELECT DISTINCT UPPER(TRIM(P.NUMORIGINAL)) AS NUMORIGINAL
  FROM PCPRODUT P
 WHERE NVL(P.REVENDA, 'S') = 'S'
   AND P.DTEXCLUSAO IS NULL
   AND P.NUMORIGINAL NOT LIKE '%VMP%'
   AND P.NUMORIGINAL NOT LIKE '%0X0001%'
   AND P.NUMORIGINAL NOT LIKE '%LOTE%'
   AND P.CODEPTO NOT IN (65 /*IMOBILIZADOS*/)
   AND P.CODMARCA NOT IN (36765 /*PATRIMONIO*/, 84 /*CONSUMO*/)
   AND LENGTH(UPPER(TRIM(P.NUMORIGINAL)))>1
   AND UPPER(TRIM(P.NUMORIGINAL)) NOT IN
       (SELECT UPPER(TRIM(B.PROD_EXTERNAL_ID)) FROM BGPRODUCT B)
ORDER BY 1 ASC