CREATE TABLE CLIFICHACADASTRALANEXO(
	IDANEXO          NUMBER(11) PRIMARY KEY,
	IDFICHACADASTRAL NUMBER(11) NOT NULL,
	TIPO             VARCHAR2(10) NOT NULL,
	ARQUIVO          VARCHAR2(100) NOT NULL
)