-- CREATE TABLE
DROP TABLE OMGCANCELADOS;
CREATE TABLE OMGCANCELADOS
(
  IDCANCELADOS     VARCHAR2(40) NOT NULL,
  NUMPED           NUMBER(10) NOT NULL,
  CODPROD          NUMBER(10) NOT NULL,
  DV               NUMBER(10),
  DESCRICAO        VARCHAR2(40),
  MARCA            VARCHAR2(20),
  LOCACAO          VARCHAR2(20),

  DATACANC         DATE NOT NULL,
  CODUSUR          NUMBER(10),
  RCA              VARCHAR2(60),
  CODCLI           NUMBER(10),
  CLIENTE          VARCHAR2(60),
  CANCELADO_POR    VARCHAR2(40),
  MOTIVO           VARCHAR2(60),
  QT               NUMBER(10) DEFAULT 0,

  IDUSURCONFERENTE NUMBER(10),
  DATACONFERENCIA  DATE,
  QTCONFERIDA      NUMBER(10) DEFAULT 0,
  OBSERVACAO       VARCHAR2(100)
);