create table ORCEQUIPTIPO
(
  IDEQUIPTIPO        NUMBER(10) not null,
  TIPO               VARCHAR2(50),
  DTCADASTO          DATE DEFAULT SYSDATE,
  IDUSURCADASTRO     NUMBER(10),
  DTULTALTERACAO     DATE,
  IDUSURULTALTERACAO NUMBER(10),
  DTEXCLUSAO         DATE,
  IDUSUREXCLUSAO     NUMBER(10)
);
