create table ORCEQUIPMONTADORA
(
  IDEQUIPMONTADORA   NUMBER(10) not null,
  MONTADORA          VARCHAR2(50),
  DTCADASTO          DATE DEFAULT SYSDATE,
  IDUSURCADASTRO     NUMBER(10),
  DTULTALTERACAO     DATE,
  IDUSURULTALTERACAO NUMBER(10),
  DTEXCLUSAO         DATE,
  IDUSUREXCLUSAO     NUMBER(10)
);