CREATE OR REPLACE VIEW VIEW_BOLT_MOV_COMERCIAL AS
SELECT '1-ONTEM' AS REFERENCIA,
       COUNT(DISTINCT (V.NUMNOTA)) AS QT_NFS,
       COUNT(DISTINCT (V.CODCLI)) AS QT_CLI,
       TO_CHAR(NVL(SUM(V.VLVENDA),0), '999G999G990D00') AS VLVENDA,
       TO_CHAR(NVL(SUM(CASE WHEN C.CARTAO = 'S' THEN V.VLVENDA ELSE 0 END),0), '999G999G990D00') AS COB_CARTOES,
       TO_CHAR(NVL(SUM(CASE WHEN V.CODCOB = '237' THEN V.VLVENDA ELSE 0 END),0), '999G999G990D00') AS COB_237,
       TO_CHAR(NVL(SUM(CASE WHEN V.CODCOB = 'C' THEN V.VLVENDA ELSE 0 END),0), '999G999G990D00') AS COB_C,
       TO_CHAR(NVL(SUM(CASE WHEN V.CODCOB = 'D' THEN V.VLVENDA WHEN V.CODCOB = 'DH' THEN V.VLVENDA ELSE 0 END),0), '999G999G990D00') AS COB_D,
       TO_CHAR(NVL(SUM(CASE WHEN V.CODCOB = 'DEP' THEN V.VLVENDA ELSE 0 END),0), '999G999G990D00') AS COB_DEP
  FROM VIEW_VENDAS_RESUMO_FATURAMENTO V, PCSUPERV S, PCCOB C
 WHERE V.CODSUPERVISOR = S.CODSUPERVISOR
   AND V.CODCOB = C.CODCOB
   AND TRUNC(V.DTSAIDA) = TRUNC(SYSDATE - 1)
UNION
SELECT '2-MES_ATUAL' AS REFERENCIA,
       COUNT(DISTINCT (V.NUMNOTA)) AS QT_NFS,
       COUNT(DISTINCT (V.CODCLI)) AS QT_CLI,
       TO_CHAR(NVL(SUM(V.VLVENDA),0), '999G999G990D00') AS VLVENDA,
       TO_CHAR(NVL(SUM(CASE WHEN C.CARTAO = 'S' THEN V.VLVENDA ELSE 0 END),0), '999G999G990D00') AS COB_CARTOES,
       TO_CHAR(NVL(SUM(CASE WHEN V.CODCOB = '237' THEN V.VLVENDA ELSE 0 END),0), '999G999G990D00') AS COB_237,
       TO_CHAR(NVL(SUM(CASE WHEN V.CODCOB = 'C' THEN V.VLVENDA ELSE 0 END),0), '999G999G990D00') AS COB_C,
       TO_CHAR(NVL(SUM(CASE WHEN V.CODCOB = 'D' THEN V.VLVENDA WHEN V.CODCOB = 'DH' THEN V.VLVENDA ELSE 0 END),0), '999G999G990D00') AS COB_D,
       TO_CHAR(NVL(SUM(CASE WHEN V.CODCOB = 'DEP' THEN V.VLVENDA ELSE 0 END),0), '999G999G990D00') AS COB_DEP
  FROM VIEW_VENDAS_RESUMO_FATURAMENTO V, PCSUPERV S, PCCOB C
 WHERE V.CODSUPERVISOR = S.CODSUPERVISOR
   AND V.CODCOB = C.CODCOB
   AND TRUNC(V.DTSAIDA) >= TRUNC(SYSDATE, 'MM')
UNION
SELECT '3-MES_PASSADO' AS REFERENCIA,
       COUNT(DISTINCT (V.NUMNOTA)) AS QT_NFS,
       COUNT(DISTINCT (V.CODCLI)) AS QT_CLI,
       TO_CHAR(NVL(SUM(V.VLVENDA),0), '999G999G990D00') AS VLVENDA,
       TO_CHAR(NVL(SUM(CASE WHEN C.CARTAO = 'S' THEN V.VLVENDA ELSE 0 END),0), '999G999G990D00') AS COB_CARTOES,
       TO_CHAR(NVL(SUM(CASE WHEN V.CODCOB = '237' THEN V.VLVENDA ELSE 0 END),0), '999G999G990D00') AS COB_237,
       TO_CHAR(NVL(SUM(CASE WHEN V.CODCOB = 'C' THEN V.VLVENDA ELSE 0 END),0), '999G999G990D00') AS COB_C,
       TO_CHAR(NVL(SUM(CASE WHEN V.CODCOB = 'D' THEN V.VLVENDA WHEN V.CODCOB = 'DH' THEN V.VLVENDA ELSE 0 END),0), '999G999G990D00') AS COB_D,
       TO_CHAR(NVL(SUM(CASE WHEN V.CODCOB = 'DEP' THEN V.VLVENDA ELSE 0 END),0), '999G999G990D00') AS COB_DEP
  FROM VIEW_VENDAS_RESUMO_FATURAMENTO V, PCSUPERV S, PCCOB C
 WHERE V.CODSUPERVISOR = S.CODSUPERVISOR
   AND V.CODCOB = C.CODCOB
   AND TRUNC(V.DTSAIDA) >= TRUNC(ADD_MONTHS (SYSDATE, -1), 'MM')
   AND TRUNC(V.DTSAIDA) < TRUNC(SYSDATE, 'MM')
UNION
SELECT '4-MESMO_MES_ANO_ANTERIOR' AS REFERENCIA,
       COUNT(DISTINCT (V.NUMNOTA)) AS QT_NFS,
       COUNT(DISTINCT (V.CODCLI)) AS QT_CLI,
       TO_CHAR(NVL(SUM(V.VLVENDA),0), '999G999G990D00') AS VLVENDA,
       TO_CHAR(NVL(SUM(CASE WHEN C.CARTAO = 'S' THEN V.VLVENDA ELSE 0 END),0), '999G999G990D00') AS COB_CARTOES,
       TO_CHAR(NVL(SUM(CASE WHEN V.CODCOB = '237' THEN V.VLVENDA ELSE 0 END),0), '999G999G990D00') AS COB_237,
       TO_CHAR(NVL(SUM(CASE WHEN V.CODCOB = 'C' THEN V.VLVENDA ELSE 0 END),0), '999G999G990D00') AS COB_C,
       TO_CHAR(NVL(SUM(CASE WHEN V.CODCOB = 'D' THEN V.VLVENDA WHEN V.CODCOB = 'DH' THEN V.VLVENDA ELSE 0 END),0), '999G999G990D00') AS COB_D,
       TO_CHAR(NVL(SUM(CASE WHEN V.CODCOB = 'DEP' THEN V.VLVENDA ELSE 0 END),0), '999G999G990D00') AS COB_DEP
  FROM VIEW_VENDAS_RESUMO_FATURAMENTO V, PCSUPERV S, PCCOB C
 WHERE V.CODSUPERVISOR = S.CODSUPERVISOR
   AND V.CODCOB = C.CODCOB
   AND TRUNC(V.DTSAIDA) >= TRUNC(ADD_MONTHS (SYSDATE, -12), 'MM')
   AND TRUNC(V.DTSAIDA) < TRUNC(ADD_MONTHS (SYSDATE, -11), 'MM')
ORDER BY REFERENCIA ASC
/**/
with read only;
