CREATE OR REPLACE VIEW VIEW_BOLT_MOV_VENDADEVOL AS
SELECT TO_CHAR(M.DTMOV, 'DD/MM/YYYY HH:II:SS') AS DATA,
       M.CODCLI,
       C.CLIENTE,
       M.NUMNOTA,
       CASE WHEN SUM(M.QT * M.PUNIT) < P.VLTOTAL THEN 'PARCIAL' ELSE 'TOTAL' END AS TIPO,
       TO_CHAR(NVL(SUM(M.QT * M.PUNIT),0), '999G999G990D00') AS VALOR,
       P.CODCOB,
       P.CODPLPAG || '- ' || PAG.DESCRICAO AS PLPAG
  FROM PCMOV M, PCCLIENT C, PCPEDC P, PCPLPAG PAG
 WHERE M.CODCLI = C.CODCLI
   AND M.NUMPED = P.NUMPED
   AND P.CODPLPAG = PAG.CODPLPAG
   AND TRUNC(M.DTMOV) = TRUNC(SYSDATE - 1)
   AND M.CODOPER = 'ED'
   AND M.DTCANCEL IS NULL
 GROUP BY M.DTMOV,
          M.CODCLI,
          C.CLIENTE,
          M.NUMNOTA,
          P.CODCOB,
          P.VLTOTAL,
          P.CODPLPAG || '- ' || PAG.DESCRICAO
 ORDER BY M.CODCLI;
