CREATE OR REPLACE VIEW VIEW_BOLT_MOV_COMPRAS AS
SELECT '1- ONTEM' AS REFERENCIA,
       COUNT(DISTINCT(M.NUMNOTA)) AS QUANT_NFS,
       COUNT(DISTINCT(M.CODFORNEC)) AS QUANT_FORN,
       TO_CHAR(NVL(ROUND(SUM(M.QT * M.PUNIT),2),0), '999G999G990D00') AS VLR_TOT
FROM PCMOV M
WHERE M.CODOPER = 'E'
AND TRUNC(M.DTMOV) = TRUNC(SYSDATE-1)
AND M.DTCANCEL IS NULL
UNION ALL
SELECT '2- MES ATUAL' AS REFERENCIA,
       COUNT(DISTINCT(M.NUMNOTA)) AS QUANT_NFS,
       COUNT(DISTINCT(M.CODFORNEC)) AS QUANT_FORN,
       TO_CHAR(NVL(ROUND(SUM(M.QT * M.PUNIT),2),0), '999G999G990D00') AS VLR_TOT
FROM PCMOV M
WHERE M.CODOPER = 'E'
AND TRUNC(M.DTMOV) >= TRUNC(SYSDATE,'MM')
AND TRUNC(M.DTMOV) <= TRUNC(LAST_DAY(SYSDATE))
AND M.DTCANCEL IS NULL
UNION ALL
SELECT '3- MESMO MES ANO ANTERIOR' AS REFERENCIA,
       COUNT(DISTINCT(M.NUMNOTA)) AS QUANT_NFS,
       COUNT(DISTINCT(M.CODFORNEC)) AS QUANT_FORN,
       TO_CHAR(NVL(ROUND(SUM(M.QT * M.PUNIT),2),0), '999G999G990D00') AS VLR_TOT
FROM PCMOV M
WHERE M.CODOPER = 'E'
AND TRUNC(M.DTMOV) >= TRUNC(ADD_MONTHS(SYSDATE,-12),'MM')
AND TRUNC(M.DTMOV) <= TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,-12)))
AND M.DTCANCEL IS NULL
UNION ALL
SELECT '4- MES PASSADO' AS REFERENCIA,
       COUNT(DISTINCT(M.NUMNOTA)) AS QUANT_NFS,
       COUNT(DISTINCT(M.CODFORNEC)) AS QUANT_FORN,
       TO_CHAR(NVL(ROUND(SUM(M.QT * M.PUNIT),2),0), '999G999G990D00') AS VLR_TOT
FROM PCMOV M
WHERE M.CODOPER = 'E'
AND TRUNC(M.DTMOV) >= TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')
AND TRUNC(M.DTMOV) <= TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,-1)))
AND M.DTCANCEL IS NULL;
