CREATE OR REPLACE VIEW VIEW_BOLT_MOV_CREDITOMENOR20 AS
SELECT BASE.CODCLI,
       BASE.CLIENTE,
       TO_CHAR(NVL(BASE.LIMCRED,0), '999G999G990D00') AS LIMCRED,
       TO_CHAR(NVL(BASE.VLARECEBER,0), '999G999G990D00') AS VLARECEBER,
       TO_CHAR(NVL(BASE.VLPENDENTE,0), '999G999G990D00') AS VLPENDENTE,
       TO_CHAR(NVL((BASE.LIMCRED - BASE.VLARECEBER - BASE.VLPENDENTE),0), '999G999G990D00') AS VLDISPONIVEL,
       ROUND((((BASE.LIMCRED - BASE.VLARECEBER - BASE.VLPENDENTE) /
             BASE.LIMCRED) * 100),
             2) AS PERCDISPONIVEL
  FROM (SELECT CLI.CODCLI,
               CLI.CLIENTE,
               ROUND(CLI.LIMCRED, 0) AS LIMCRED,
               NVL((SELECT ROUND(SUM(P.VALOR), 0) AS VLARECEBER
                  FROM PCPREST P
                 WHERE CLI.CODCLI = P.CODCLI
                   AND P.DTPAG IS NULL
                   AND P.DTCANCEL IS NULL),0) AS VLARECEBER,
               NVL((SELECT ROUND(SUM(PI.QT * PI.PVENDA), 0) AS VLPENDENTE
                  FROM PCPEDC PC, PCPEDI PI
                 WHERE CLI.CODCLI = PC.CODCLI
                   AND PC.NUMPED = PI.NUMPED
                   AND PC.POSICAO <> 'F'
                   AND PC.DTCANCEL IS NULL),0) AS VLPENDENTE
          FROM PCCLIENT CLI
         GROUP BY CLI.CODCLI, CLI.CLIENTE, CLI.LIMCRED) BASE
 WHERE BASE.LIMCRED > 1
   AND ((BASE.LIMCRED - BASE.VLARECEBER - BASE.VLPENDENTE) /
       BASE.LIMCRED) <= 0.2
   ORDER BY BASE.LIMCRED DESC, (BASE.LIMCRED - BASE.VLARECEBER - BASE.VLPENDENTE)  ASC;
