CREATE OR REPLACE VIEW VIEW_BOLT_MOV_CREDITOABERTO AS
SELECT BASE.CODCLI,
BASE.CLIENTE,
BASE.CREDITO_DISP,
BASE.LIMITE_TOTAL,
(NVL(BASE.VLARECEBER,0) + NVL(BASE.VLPENDENTE,0)) AS LIMITE_USO,
(NVL(BASE.LIMITE_TOTAL,0) - (NVL(BASE.VLARECEBER,0) + NVL(BASE.VLPENDENTE,0))) AS LIMITE_DISP

FROM (SELECT CLI.CODCLI,
       CLI.CLIENTE,
       SUM(CRE.VALOR) CREDITO_DISP,
       ROUND(CLI.LIMCRED, 0) AS LIMITE_TOTAL,
   NVL((SELECT ROUND(SUM(P.VALOR), 0) AS VLARECEBER
      FROM PCPREST P
     WHERE CLI.CODCLI = P.CODCLI
       AND P.DTPAG IS NULL
       AND P.DTCANCEL IS NULL),0) AS VLARECEBER,
   NVL((SELECT ROUND(SUM(PI.QT * PI.PVENDA), 0) AS VLPENDENTE
      FROM PCPEDC PC, PCPEDI PI
     WHERE CLI.CODCLI = PC.CODCLI
       AND PC.NUMPED = PI.NUMPED
       AND PC.POSICAO <> 'F'
       AND PC.DTCANCEL IS NULL),0) AS VLPENDENTE
  FROM PCCRECLI CRE, PCCLIENT CLI
 WHERE CRE.CODCLI = CLI.CODCLI
   AND CRE.DTDESCONTO IS NULL
 GROUP BY CLI.CODCLI, CLI.CLIENTE, CLI.LIMCRED) BASE
 ORDER BY BASE.CLIENTE;
