CREATE OR REPLACE VIEW VIEWEFCOTACAO AS
(
SELECT "ORIGEM","CODPECA","NUMORIGINAL","IDCOTACOES","DATA","VENDEDOR","CLIENTE","PRODUTO","MARCAALFA","QUANTIDADE","PRECO" FROM (
      SELECT   TO_CHAR('WINT') AS ORIGEM,
               TO_CHAR(I.CODPECA) AS CODPECA,
               TO_CHAR(I.NUMORIGINAL) AS NUMORIGINAL,
               TO_CHAR(C.IDORCAMENTO) AS IDCOTACOES,
               TRUNC (C.DATA) AS DATA,
               TO_CHAR(U.NOME) AS VENDEDOR,
               TO_CHAR(CLI.CODCLI||'- '||CLI.FANTASIA) AS CLIENTE,
               TO_CHAR(I.CODPROD||'- '||I.DESCRICAO) AS PRODUTO,
               TO_CHAR(I.MARCA) AS MARCAALFA,
               TO_CHAR(I.QTPEDIDA) AS QUANTIDADE,
               TO_CHAR(I.PTABELA) AS PRECO
        FROM   ORCORCAMENTOC C
        LEFT JOIN ORCORCAMENTOI I ON C.IDORCAMENTO = I.IDORCAMENTO
        LEFT JOIN ORCUSUARIO U ON C.IDUSUARIO = U.IDUSUARIO
        LEFT JOIN PCCLIENT CLI ON C.CODCLI = CLI.CODCLI
UNION
  SELECT   TO_CHAR('RADAR') AS ORIGEM,
               TO_CHAR(C.PRODUTO) AS CODPECA,
               TO_CHAR(C.PRODUTO) AS NUMORIGINAL,
               TO_CHAR(C.IDCOTACOES) AS IDCOTACOES,
               C.DATA,
               TO_CHAR(C.VENDEDOR) AS VENDEDOR,
               TO_CHAR(C.CLIENTE) AS CLIENTE,
               TO_CHAR(C.PRODUTO) AS PRODUTO,
               TO_CHAR('') AS MARCAALFA,
               TO_CHAR(C.QUANTIDADE) AS QUANTIDADE,
               TO_CHAR(C.PRECO) AS PRECO
        FROM   ORCRADARCOTACOES C
  )
) ORDER BY DATA DESC;
