CREATE OR REPLACE VIEW VIEW_BOLT_MOV_CONTA_REC_FUTURO AS
SELECT PCPREST.CODCOB,
       'VENC 015 DIAS' AS VENCIMENTOS,
       SUM(PCPREST.VALORORIG) AS VLTOTAL
  FROM PCPREST, PCCLIENT
 WHERE PCPREST.CODCLI = PCCLIENT.CODCLI
   AND PCPREST.STATUS = 'A'
   AND PCPREST.DTPAG IS NULL
   AND PCPREST.CODCOB IN ('237', 'C')
   AND TRUNC(PCPREST.DTVENC) >= TRUNC(SYSDATE)
   AND (TRUNC(PCPREST.DTVENC) - TRUNC(SYSDATE)) < 15
 GROUP BY PCPREST.CODCOB
 UNION
 SELECT PCPREST.CODCOB,
       'VENC 030 DIAS' AS VENCIMENTOS,
       SUM(PCPREST.VALORORIG) AS VLTOTAL
  FROM PCPREST, PCCLIENT
 WHERE PCPREST.CODCLI = PCCLIENT.CODCLI
   AND PCPREST.STATUS = 'A'
   AND PCPREST.DTPAG IS NULL
   AND PCPREST.CODCOB IN ('237', 'C')
   AND TRUNC(PCPREST.DTVENC) >= TRUNC(SYSDATE)
   AND (TRUNC(PCPREST.DTVENC) - TRUNC(SYSDATE)) >= 15
   AND (TRUNC(PCPREST.DTVENC) - TRUNC(SYSDATE)) < 30
 GROUP BY PCPREST.CODCOB
 UNION
 SELECT PCPREST.CODCOB,
       'VENC 045 DIAS' AS VENCIMENTOS,
       SUM(PCPREST.VALORORIG) AS VLTOTAL
  FROM PCPREST, PCCLIENT
 WHERE PCPREST.CODCLI = PCCLIENT.CODCLI
   AND PCPREST.STATUS = 'A'
   AND PCPREST.DTPAG IS NULL
   AND PCPREST.CODCOB IN ('237', 'C')
   AND TRUNC(PCPREST.DTVENC) >= TRUNC(SYSDATE)
   AND (TRUNC(PCPREST.DTVENC) - TRUNC(SYSDATE)) >= 30
   AND (TRUNC(PCPREST.DTVENC) - TRUNC(SYSDATE)) < 45
 GROUP BY PCPREST.CODCOB
 UNION
 SELECT PCPREST.CODCOB,
       'VENC 060 DIAS' AS VENCIMENTOS,
       SUM(PCPREST.VALORORIG) AS VLTOTAL
  FROM PCPREST, PCCLIENT
 WHERE PCPREST.CODCLI = PCCLIENT.CODCLI
   AND PCPREST.STATUS = 'A'
   AND PCPREST.DTPAG IS NULL
   AND PCPREST.CODCOB IN ('237', 'C')
   AND TRUNC(PCPREST.DTVENC) >= TRUNC(SYSDATE)
   AND (TRUNC(PCPREST.DTVENC) - TRUNC(SYSDATE)) >= 45
   AND (TRUNC(PCPREST.DTVENC) - TRUNC(SYSDATE)) < 60
 GROUP BY PCPREST.CODCOB
 UNION
 SELECT PCPREST.CODCOB,
       'VENC 090 DIAS' AS VENCIMENTOS,
       SUM(PCPREST.VALORORIG) AS VLTOTAL
  FROM PCPREST, PCCLIENT
 WHERE PCPREST.CODCLI = PCCLIENT.CODCLI
   AND PCPREST.STATUS = 'A'
   AND PCPREST.DTPAG IS NULL
   AND PCPREST.CODCOB IN ('237', 'C')
   AND TRUNC(PCPREST.DTVENC) >= TRUNC(SYSDATE)
   AND (TRUNC(PCPREST.DTVENC) - TRUNC(SYSDATE)) >= 60
   AND (TRUNC(PCPREST.DTVENC) - TRUNC(SYSDATE)) < 90
 GROUP BY PCPREST.CODCOB
 UNION
 SELECT PCPREST.CODCOB,
       'VENC 120 DIAS' AS VENCIMENTOS,
       SUM(PCPREST.VALORORIG) AS VLTOTAL
  FROM PCPREST, PCCLIENT
 WHERE PCPREST.CODCLI = PCCLIENT.CODCLI
   AND PCPREST.STATUS = 'A'
   AND PCPREST.DTPAG IS NULL
   AND PCPREST.CODCOB IN ('237', 'C')
   AND TRUNC(PCPREST.DTVENC) >= TRUNC(SYSDATE)
   AND (TRUNC(PCPREST.DTVENC) - TRUNC(SYSDATE)) >= 90
   AND (TRUNC(PCPREST.DTVENC) - TRUNC(SYSDATE)) < 120
 GROUP BY PCPREST.CODCOB
 UNION
 SELECT PCPREST.CODCOB,
       'VENC MAIOR 120 DIAS' AS VENCIMENTOS,
       SUM(PCPREST.VALORORIG) AS VLTOTAL
  FROM PCPREST, PCCLIENT
 WHERE PCPREST.CODCLI = PCCLIENT.CODCLI
   AND PCPREST.STATUS = 'A'
   AND PCPREST.DTPAG IS NULL
   AND PCPREST.CODCOB IN ('237', 'C')
   AND TRUNC(PCPREST.DTVENC) >= TRUNC(SYSDATE)
   AND (TRUNC(PCPREST.DTVENC) - TRUNC(SYSDATE)) >= 120
 GROUP BY PCPREST.CODCOB
 ORDER BY 1, 2 ASC;
