CREATE OR REPLACE VIEW VIEWEFCOMPRA AS
(SELECT TO_CHAR(PCMOV.DTMOV, 'DD/MM/YYYY') AS DATA,
       PCMOV.DTMOV,
       NVL(PCMOV.CODOPER, 'X') AS CODOPER,
       PCCLIENT.CODCLI,
       PCPRODUT.CODPROD,
       PCPRODUT.NUMORIGINAL AS PRODUTO,
       PCCLIENT.CLIENTE,
       PCMOV.QT AS QUANTIDADE,
       PCMOV.PUNIT AS PRECO,
       NVL((SELECT PCMARCA.MARCA
             FROM PCMARCA
            WHERE PCMARCA.CODMARCA = PCPRODUT.CODMARCA),
           PCPRODUT.MARCA) AS MARCAALFA
  FROM PCMOV, PCPRODUT, PCCLIENT
 WHERE (PCMOV.CODPROD = PCPRODUT.CODPROD)
   AND (PCMOV.CODCLI = PCCLIENT.CODCLI)
   AND PCMOV.DTCANCEL IS NULL
   AND NVL(PCMOV.CODOPER, 'X') IN ('E')
);
