CREATE OR REPLACE VIEW VIEW_BOLT_OCOR_VENDALIBERADA AS
SELECT TO_CHAR(C.DTLIBERA, 'DD/MM/YYYY HH:II:SS') AS DATA,
       C.CODCLI,
       CLI.CLIENTE,
       C.NUMPED,
       C.NUMNOTA,
       TO_CHAR(NVL(C.VLTOTAL,0), '999G999G990D00') AS VLTOTAL,
       C.CODCOB,
       C.CODPLPAG||'- '||P.DESCRICAO AS PLPAG,
       C.CODFUNCLIBERA||'- '||E.NOME AS USUARIO
FROM PCPEDC C, PCCLIENT CLI, PCEMPR E, PCPLPAG P
WHERE C.CODCLI = CLI.CODCLI
AND C.CODFUNCLIBERA = E.MATRICULA
AND C.CODPLPAG = P.CODPLPAG
AND TRUNC(C.DTLIBERA) = TRUNC(SYSDATE-1);
