CREATE OR REPLACE VIEW VIEW_BOLT_OCO_VENDAS_CARTOES AS
SELECT PCPREST.DUPLIC,
       TO_CHAR(PCPREST.DTEMISSAO, 'DD/MM/YYYY HH:II:SS') AS DTEMISSAO,
       PCPREST.CODCLI,
       PCCLIENT.CLIENTE,
       PCPREST.VALORORIG AS VL_TITULO,
       PCPREST.VALORDESC AS VL_DESC,
       (NVL(PCPREST.VALORORIG, 0) - NVL(PCPREST.VALORDESC, 0)) AS VL_LIQ,
       PCPREST.CODCOB
  FROM PCPREST, PCCLIENT
 WHERE PCPREST.CODCLI = PCCLIENT.CODCLI
   AND PCPREST.STATUS = 'A'
   AND PCPREST.CODCLI = 14613
   AND TRUNC(PCPREST.DTEMISSAO) =
       (SELECT TRUNC(MAX(PCDIASUTEIS.DATA)) AS ULTIMODIAUTIL
          FROM PCDIASUTEIS
         WHERE CODFILIAL = 1
           AND TRUNC(PCDIASUTEIS.DATA) <= TRUNC(SYSDATE - 1)
           AND PCDIASUTEIS.DIAVENDAS = 'S')
 ORDER BY PCPREST.CODCOB;
