CREATE OR REPLACE VIEW VIEW_BOLT_MOV_CONTASRECEBER AS
SELECT 15 AS DIAS,
       TO_CHAR(SUM(NVL(DECODE(P.CODCOB, '237', P.VALOR, 0), 0)),
               '999G999G990D00') AS "237",
       TO_CHAR(SUM(NVL(DECODE(P.CODCOB, 'C', P.VALOR, 0), 0)),
               '999G999G990D00') AS "C"
  FROM PCPREST P, PCCLIENT C
 WHERE P.CODCLI = C.CODCLI
   AND P.DTPAG IS NULL
   AND P.CODCOB IN ('237', 'C')
   AND P.DTVENC <= TRUNC(SYSDATE + 15)
UNION
SELECT 30 AS DIAS,
       TO_CHAR(SUM(NVL(DECODE(P.CODCOB, '237', P.VALOR, 0), 0)),
               '999G999G990D00') AS "237",
       TO_CHAR(SUM(NVL(DECODE(P.CODCOB, 'C', P.VALOR, 0), 0)),
               '999G999G990D00') AS "C"
  FROM PCPREST P, PCCLIENT C
 WHERE P.CODCLI = C.CODCLI
   AND P.DTPAG IS NULL
   AND P.CODCOB IN ('237', 'C')
   AND P.DTVENC > TRUNC(SYSDATE + 15)
   AND P.DTVENC <= TRUNC(SYSDATE + 30)
UNION
SELECT 45 AS DIAS,
       TO_CHAR(SUM(NVL(DECODE(P.CODCOB, '237', P.VALOR, 0), 0)),
               '999G999G990D00') AS "237",
       TO_CHAR(SUM(NVL(DECODE(P.CODCOB, 'C', P.VALOR, 0), 0)),
               '999G999G990D00') AS "C"
  FROM PCPREST P, PCCLIENT C
 WHERE P.CODCLI = C.CODCLI
   AND P.DTPAG IS NULL
   AND P.CODCOB IN ('237', 'C')
   AND P.DTVENC > TRUNC(SYSDATE + 30)
   AND P.DTVENC <= TRUNC(SYSDATE + 45)
UNION
SELECT 60 AS DIAS,
       TO_CHAR(SUM(NVL(DECODE(P.CODCOB, '237', P.VALOR, 0), 0)),
               '999G999G990D00') AS "237",
       TO_CHAR(SUM(NVL(DECODE(P.CODCOB, 'C', P.VALOR, 0), 0)),
               '999G999G990D00') AS "C"
  FROM PCPREST P, PCCLIENT C
 WHERE P.CODCLI = C.CODCLI
   AND P.DTPAG IS NULL
   AND P.CODCOB IN ('237', 'C')
   AND P.DTVENC > TRUNC(SYSDATE + 45)
   AND P.DTVENC <= TRUNC(SYSDATE + 60)
UNION
SELECT 90 AS DIAS,
       TO_CHAR(SUM(NVL(DECODE(P.CODCOB, '237', P.VALOR, 0), 0)),
               '999G999G990D00') AS "237",
       TO_CHAR(SUM(NVL(DECODE(P.CODCOB, 'C', P.VALOR, 0), 0)),
               '999G999G990D00') AS "C"
  FROM PCPREST P, PCCLIENT C
 WHERE P.CODCLI = C.CODCLI
   AND P.DTPAG IS NULL
   AND P.CODCOB IN ('237', 'C')
   AND P.DTVENC > TRUNC(SYSDATE + 60)
   AND P.DTVENC <= TRUNC(SYSDATE + 90)
UNION
SELECT 120 AS DIAS,
       TO_CHAR(SUM(NVL(DECODE(P.CODCOB, '237', P.VALOR, 0), 0)),
               '999G999G990D00') AS "237",
       TO_CHAR(SUM(NVL(DECODE(P.CODCOB, 'C', P.VALOR, 0), 0)),
               '999G999G990D00') AS "C"
  FROM PCPREST P, PCCLIENT C
 WHERE P.CODCLI = C.CODCLI
   AND P.DTPAG IS NULL
   AND P.CODCOB IN ('237', 'C')
   AND P.DTVENC > TRUNC(SYSDATE + 90)
   AND P.DTVENC <= TRUNC(SYSDATE + 120)
ORDER BY 1 ASC;
