CREATE OR REPLACE VIEW VIEW_BOLT_MOV_CONTA_REC_PEND AS
SELECT PCPREST.CODCLI,
       PCCLIENT.CLIENTE,
       TO_CHAR(PCPREST.DTVENC, 'DD/MM/YYYY HH:II:SS') AS DTVENC,
       (TRUNC(SYSDATE) - TRUNC(PCPREST.DTVENC)) AS DIAS_VENC,
       PCPREST.DUPLIC,
       PCPREST.PREST,
       PCPREST.VALORORIG AS VL_TITULO,
       PCPREST.CODCOB,
       (SELECT TO_CHAR(PCHISTCOB.DATA, 'DD/MM/YYYY HH:II:SS') || ' - ' ||
               PCHISTCOB.OBS1 || ' ' || PCHISTCOB.OBS2 || ' ' ||
               PCHISTCOB.OBS3 AS HISTORICO
          FROM PCHISTCOB
         WHERE PCHISTCOB.CODCLI = PCPREST.CODCLI
           AND PCHISTCOB.NUMREGCOB =
               (SELECT MAX(H.NUMREGCOB)
                  FROM PCHISTCOB H
                 WHERE H.CODCLI = PCHISTCOB.CODCLI)) AS HIST_1,

       (SELECT TO_CHAR(PCHISTCOB.DATA, 'DD/MM/YYYY HH:II:SS') || ' - ' ||
               PCHISTCOB.OBS1 || ' ' || PCHISTCOB.OBS2 || ' ' ||
               PCHISTCOB.OBS3 AS HISTORICO
          FROM PCHISTCOB
         WHERE PCHISTCOB.CODCLI = PCPREST.CODCLI
           AND PCHISTCOB.NUMREGCOB =
               (SELECT MAX(H.NUMREGCOB)
                  FROM PCHISTCOB H
                 WHERE H.CODCLI = PCHISTCOB.CODCLI
                   AND H.NUMREGCOB <>
                       (SELECT MAX(H2.NUMREGCOB)
                          FROM PCHISTCOB H2
                         WHERE H2.CODCLI = PCHISTCOB.CODCLI))) AS HIST_2,

       (SELECT TO_CHAR(PCHISTCOB.DATA, 'DD/MM/YYYY HH:II:SS') || ' - ' ||
               PCHISTCOB.OBS1 || ' ' || PCHISTCOB.OBS2 || ' ' ||
               PCHISTCOB.OBS3 AS HISTORICO
          FROM PCHISTCOB
         WHERE PCHISTCOB.CODCLI = PCPREST.CODCLI
           AND PCHISTCOB.NUMREGCOB =
               (SELECT MAX(H.NUMREGCOB)
                  FROM PCHISTCOB H
                 WHERE H.CODCLI = PCHISTCOB.CODCLI
                   AND H.NUMREGCOB <>
                       (SELECT MAX(H2.NUMREGCOB)
                          FROM PCHISTCOB H2
                         WHERE H2.CODCLI = PCHISTCOB.CODCLI)
                   AND H.NUMREGCOB <>
                       (SELECT MAX(H2.NUMREGCOB)
                          FROM PCHISTCOB H2
                         WHERE H2.CODCLI = PCHISTCOB.CODCLI))) AS HIST_3
  FROM PCPREST, PCCLIENT
 WHERE PCPREST.CODCLI = PCCLIENT.CODCLI
   AND PCPREST.STATUS = 'A'
   AND PCPREST.DTPAG IS NULL
   AND PCPREST.CODCOB IN ('237', 'C')
   AND TRUNC(PCPREST.DTVENC) < TRUNC(SYSDATE)
 ORDER BY PCCLIENT.CLIENTE;
