CREATE OR REPLACE VIEW VIEWEFCOMPRAS AS
SELECT "ORIGEM","CODPECA","DATA","FORNECEDOR","PRODUTO","MARCAALFA","QUANTIDADE","PRECO" FROM
(
SELECT   DISTINCT TO_CHAR ('WINT') AS ORIGEM,
                  TO_CHAR (P.NUMORIGINAL) AS CODPECA,
                  M.DTMOV AS DATA,
                  F.CODFORNEC||'- '||F.FORNECEDOR AS FORNECEDOR,
                  P.CODPROD||'- '||P.DESCRICAO AS PRODUTO,
                  MA.MARCA AS MARCAALFA,
                  TO_CHAR(M.QT) AS QUANTIDADE,
                  TO_CHAR(M.PUNIT) AS PRECO
  FROM   PCMOV M
  LEFT JOIN PCPRODUT P ON (M.CODPROD = P.CODPROD)
  LEFT JOIN PCFORNEC F ON (M.CODFORNEC = F.CODFORNEC)
  LEFT JOIN PCMARCA MA ON (P.CODMARCA = MA.CODMARCA)
  WHERE M.CODOPER = 'E'
    AND M.DTCANCEL IS NULL
UNION
SELECT   DISTINCT TO_CHAR ('RADAR') AS ORIGEM,
                  TO_CHAR (C.PRODUTO) AS CODPECA,
                  C.DATA,
                  C.CLIENTE AS FORNECEDOR,
                  C.PRODUTO,
                  C.MARCAALFA,
                  C.QUANTIDADE,
                  C.PRECO
  FROM   ORCCOMPRAS C
) ORDER BY DATA DESC;
