CREATE OR REPLACE VIEW VIEW_BOLT_OCOR_PEDIDOPENDENTE AS
SELECT C.NUMPED,
       TO_CHAR(C.DATA, 'DD/MM/YYYY HH:II:SS') AS DATA,
       C2.CODCLI,
       C2.CLIENTE,
       C.VLTOTAL,
       C.CODCOB,
       P.DESCRICAO AS PLPAG,
       C.POSICAO
  FROM PCPEDC C, PCCLIENT C2, PCPLPAG P
 WHERE C.CODCLI = C2.CODCLI
   AND C.CODPLPAG = P.CODPLPAG
   AND C.DTCANCEL IS NULL
   AND C.POSICAO NOT IN ('F', 'C')
 ORDER BY NUMPED ASC;
