CREATE OR REPLACE VIEW VIEW_BOLT_OCOR_LIMCREDALT AS
SELECT TO_CHAR(A.DTALTERACAO, 'DD/MM/YYYY HH:II:SS') AS DATA,
       A.CODCLI,
       C.CLIENTE,
       dbms_lob.substr( A.VALORANT, 4000, 1 ) AS VALORANT,
       dbms_lob.substr( A.VALORATU, 4000, 1 ) AS VALORATU,
       A.MATRICULA||'- '||E.NOME AS USUARIO
FROM PCLOGALTCLI A, PCCLIENT C, PCEMPR E
WHERE A.CODCLI = C.CODCLI
AND A.MATRICULA = E.MATRICULA
AND A.ROTINA LIKE '%1203%'
AND A.CAMPO LIKE '%LIM%'
AND TRUNC(A.DTALTERACAO) = TRUNC(SYSDATE-1)
ORDER BY A.DTALTERACAO DESC;
