CREATE OR REPLACE VIEW VIEW_BOLT_OCOR_CADCCLI AS
SELECT TO_CHAR(C.DTCADASTRO, 'DD/MM/YYYY HH:II:SS') AS DATA,
       C.CODCLI,
       C.CLIENTE,
       C.MUNICENT AS CIDADE,
       C.ESTENT AS UF,
       C.CODCOB,
       C.CODPLPAG,
       C.LIMCRED,
       C.CODFUNCCADASTRO||'- '||E.NOME AS USUARIO
FROM PCCLIENT C, PCEMPR E
WHERE C.CODFUNCCADASTRO = E.MATRICULA
AND TRUNC(C.DTCADASTRO) = TRUNC(SYSDATE-1)
ORDER BY C.DTCADASTRO ASC;
