CREATE OR REPLACE VIEW VIEW_BOLT_MOV_DEVOLFORNEC AS
SELECT TO_CHAR(M.DTMOV, 'DD/MM/YYYY HH:II:SS') AS DATA,
       M.CODFORNEC,
       F.FORNECEDOR,
       M.NUMNOTA,
       CASE WHEN SUM(M.QT * M.PUNIT) < S.VLTOTAL THEN 'PARCIAL' ELSE 'TOTAL' END AS TIPO,
       TO_CHAR(NVL(SUM(M.QT * M.PUNIT),0), '999G999G990D00') AS VALOR,
       S.CODCOB,
       S.CODPLPAG
  FROM PCMOV M, PCFORNEC F, PCNFSAID S
 WHERE M.CODFORNEC = F.CODFORNEC
   AND M.NUMNOTA = S.NUMNOTA
   AND M.NUMTRANSVENDA = S.NUMTRANSVENDA
   AND TRUNC(M.DTMOV) = TRUNC(SYSDATE - 1)
   AND M.CODOPER = 'SD'
   AND M.DTCANCEL IS NULL
 GROUP BY M.DTMOV,
          M.CODFORNEC,
          F.FORNECEDOR,
          M.NUMNOTA,
          S.VLTOTAL,
          S.CODCOB,
          S.CODPLPAG
 ORDER BY M.CODFORNEC;
