CREATE OR REPLACE VIEW VIEW_BOLT_MOV_SALDOBANCO AS
SELECT PCBANCO.CODBANCO, ESTCR.VALORCONCILIADO, MOVCR.VALORDEBITO, MOVCR.VALORCREDITO, ESTCR.VALORATUAL
FROM PCBANCO,
(SELECT PCMOVCR.CODBANCO,
       TO_CHAR(SUM(DECODE(PCMOVCR.TIPO, 'D', PCMOVCR.VALOR, 0)),
               '999G999G990D00') AS VALORDEBITO,
       TO_CHAR(SUM(DECODE(PCMOVCR.TIPO, 'C', PCMOVCR.VALOR, 0)),
               '999G999G990D00') AS VALORCREDITO
  FROM PCMOVCR
 WHERE PCMOVCR.DTCONCIL IS NULL
   AND PCMOVCR.CODCOB IN ('D')
 GROUP BY PCMOVCR.CODBANCO) MOVCR,
(SELECT PCESTCR.CODBANCO,
       TO_CHAR(NVL(PCESTCR.VALORCONCILIADO, 0), '999G999G990D00') AS VALORCONCILIADO,
       TO_CHAR(NVL(PCESTCR.VALOR, 0), '999G999G990D00') AS VALORATUAL
  FROM PCESTCR
 WHERE PCESTCR.CODCOB = 'D'
   AND PCESTCR.DTULTCOMPENSACAO IS NOT NULL) ESTCR
WHERE PCBANCO.CODBANCO = MOVCR.CODBANCO
AND PCBANCO.CODBANCO = ESTCR.CODBANCO
AND PCBANCO.CODBANCO IN (237, 10, 13, 133);
