-- Tabela de Notificações com Prefixo VMP_
CREATE TABLE VMP_NOTIFICACAO (
    ID_NOTIFICACAO       NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_CHAMADO           NUMBER(19) NOT NULL,
    ID_USUARIO_DESTINO   NUMBER(19) NOT NULL, -- Quem recebe
    ID_USUARIO_REMETENTE NUMBER(19),          -- Quem gerou a ação (NULL para sistema)
    TX_MENSAGEM          VARCHAR2(500) NOT NULL,
    DT_EVENTO            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ST_LIDA              CHAR(1) DEFAULT 'N' CHECK (ST_LIDA IN ('S', 'N'))
);

-- Índice de performance para busca de não lidas (Polling)
CREATE INDEX IDX_VMP_NOTIF_BUSCA ON VMP_NOTIFICACAO (ID_USUARIO_DESTINO, ST_LIDA, DT_EVENTO DESC);

-- Índice de apoio para rastreabilidade de chamados
CREATE INDEX IDX_VMP_NOTIF_CHAMADO ON VMP_NOTIFICACAO (ID_CHAMADO);

COMMENT ON COLUMN VMP_NOTIFICACAO.ID_USUARIO_REMETENTE IS 'ID do usuário que realizou a ação. Se nulo, considerar ação automática do sistema.';